<?php

declare(strict_types=1);

/*
 * Dados iniciais (demonstração) — convertidos de src/data/initialData.ts e
 * src/data/analyticsData.ts da versão React. Usados pelo instalador e pelo
 * botão "Restaurar Padrão de Demonstração".
 *
 * Listas de leads e depoimentos estão na mesma ordem de exibição do original
 * (mais recente primeiro); o seeder as insere de trás para frente.
 */

$imgPasta = 'assets/img/pasta-termica.jpg';
$imgWorkstation = 'assets/img/workstation.jpg';
$imgBancada = 'assets/img/bancada-diagnostico.jpg';

return [
    'settings' => [
        'name' => 'PC Resolve',
        'corporateName' => 'PC Resolve Tecnologia & Assistência Técnica LTDA',
        'cnpj' => '38.452.190/0001-44',
        'phone' => '(83) 3031-2020',
        'whatsapp' => '(83) 98822-1010',
        'email' => 'contato@pcresolvejp.com.br',
        'address' => 'Av. Gov. Flávio Ribeiro Coutinho, 500 - Sala 402 - Manaíra',
        'neighborhood' => 'Manaíra',
        'city' => 'João Pessoa',
        'state' => 'PB',
        'zipCode' => '58038-000',
        'workingHoursWeekday' => 'Segunda a Sexta: 08h às 18h',
        'workingHoursSaturday' => 'Sábado: 08h às 12h',
        'aboutText' => 'A PC Resolve atua em João Pessoa e região metropolitana com a missão de oferecer uma assistência técnica diferenciada, que combina honestidade, rigor em bancada com proteção ESD e total respeito pelos equipamentos e dados confidenciais dos clientes.',
        'mission' => 'Prover soluções técnicas em informática que prolonguem a vida útil de computadores e notebooks com transparência, excelência de diagnóstico e preço justo.',
        'warrantyTerm' => 'Garantia legal de 90 (noventa) dias sobre todos os serviços executados e componentes substituídos, conforme o Código de Defesa do Consumidor (CDC art. 26).',
        'ga4MeasurementId' => 'G-PCRESOLVEPB',
        'gtmContainerId' => 'GTM-PCR88JP',
        'googleAdsConversionId' => 'AW-1122334455',
        'metaTitleDefault' => 'PC Resolve | Assistência Técnica de Computadores e Notebooks em João Pessoa',
        'metaDescriptionDefault' => 'Manutenção, diagnóstico e suporte técnico para computadores e notebooks em João Pessoa e cidades da região metropolitana. Bancada ESD e garantia de 90 dias.',
        'defaultWhatsappMessage' => 'Olá! Gostaria de solicitar um orçamento técnico na PC Resolve.',
    ],

    'services' => [
        [
            'slug' => 'manutencao-notebooks',
            'title' => 'Manutenção de Notebooks',
            'short_desc' => 'Reparo de carcaças, dobradiças, troca de telas, teclado e recuperação eletrônica de placa-mãe.',
            'full_desc' => 'Diagnóstico especializado em bancada técnica ESD para notebooks de todas as marcas (Dell, Lenovo, HP, Acer, Asus, Apple e Samsung). Realizamos reparos em dobradiças quebradas, recuperação de carcaça, substituição de telas IPS/OLED, teclados retroiluminados, baterias internas e reparo de circuito de carga na placa-mãe.',
            'category' => 'hardware',
            'price_starting_at' => 120,
            'turnaround_time' => '24h a 48h úteis',
            'warranty_days' => 90,
            'icon_name' => 'Laptop',
            'image' => $imgPasta,
            'highlights' => [
                'Bancada equipada com manta antiestática e microscópio óptico',
                'Troca de telas FHD e 4K com calibração de cores',
                'Restauração estrutural de dobradiças sem gambiarras',
                'Testes térmicos sob estresse de 30 minutos',
            ],
            'recommended_for' => [
                'Notebook não liga ou desliga sozinho repentinamente',
                'Tela rachada, listrada ou sem retroiluminação',
                'Tampa dura ou estalando ao abrir',
                'Teclas falhando ou teclado molhado',
            ],
        ],
        [
            'slug' => 'manutencao-computadores',
            'title' => 'Manutenção de Computadores Desktop',
            'short_desc' => 'Montagem personalizada de desktops, troca de fonte, testes térmicos e organização profissional de cabos.',
            'full_desc' => 'Atendimento completo para computadores residenciais, estações de trabalho profissionais (workstations) e PCs gamer. Realizamos montagem criteriosa com cable management de alta precisão, dimensionamento correto de fontes de alimentação selo 80 Plus, testes de estabilidade de memória e fluxo de ar.',
            'category' => 'hardware',
            'price_starting_at' => 90,
            'turnaround_time' => '24h a 48h úteis',
            'warranty_days' => 90,
            'icon_name' => 'Cpu',
            'image' => $imgWorkstation,
            'highlights' => [
                'Organização estética de cabeamento e air-flow balanceado',
                'Diagnóstico de fontes com testador digital calibrado',
                'Configuração otimizada de BIOS/UEFI e perfis XMP/EXPO',
                'Testes de carga com FurMark e Cinebench',
            ],
            'recommended_for' => [
                'PC reiniciando durante jogos ou tarefas pesadas',
                'Montagem de peças compradas pela internet',
                'Ruído excessivo de ventoinhas ou zumbido elétrico',
                'Máquina que emite bips ou não dá sinal no monitor',
            ],
        ],
        [
            'slug' => 'upgrade-ssd-memoria',
            'title' => 'Upgrade de SSD e Memória RAM',
            'short_desc' => 'Aumento expressivo de velocidade em até 10x com SSDs NVMe e clonagem de sistema sem perda de arquivos.',
            'full_desc' => 'Multiplique a performance do seu computador ou notebook. Substituímos discos rígidos mecânicos lentos (HDDs) por unidades SSD SATA ou NVMe M.2 de alta velocidade de leitura/escrita. Clonamos todo o sistema com seus programas, senhas e arquivos exatamente como estavam, sem necessidade de reconfiguração.',
            'category' => 'hardware',
            'price_starting_at' => 150,
            'turnaround_time' => 'Mesmo dia (3 a 6 horas)',
            'warranty_days' => 90,
            'icon_name' => 'Zap',
            'image' => $imgBancada,
            'highlights' => [
                'Inicialização do Windows em menos de 12 segundos',
                'Clonagem bit a bit segura de disco rígido sem perda de fotos ou documentos',
                'Memórias em Dual Channel para ganho instantâneo de FPS e multitarefas',
                'SSDs de primeira linha com garantia de fábrica',
            ],
            'recommended_for' => [
                'Computador demora 5 a 10 minutos para ligar',
                'Travamentos constantes ao abrir navegador com muitas abas',
                'Uso de 100% de disco indicado no Gerenciador de Tarefas',
                'Falta de espaço para programas pesados ou trabalho',
            ],
        ],
        [
            'slug' => 'diagnostico-reparo-hardware',
            'title' => 'Diagnóstico e Reparo de Placas Eletrônicas',
            'short_desc' => 'Análise minuciosa de curto em bancada, reparo eletrônico de placas e substituição de componentes SMD.',
            'full_desc' => 'Recuperação de placas-mãe em nível de componente eletrônico SMD. Identificamos com câmera térmica e multímetro de precisão curtos-circuitos em linhas de alimentação primária (19V, 5V, 3.3V) e secundária (VCORE, GPU). Substituímos MOSFETs, controladores PWM e capacitores em curto sem necessidade de trocar a placa inteira.',
            'category' => 'hardware',
            'price_starting_at' => 180,
            'turnaround_time' => '48h a 72h úteis',
            'warranty_days' => 90,
            'icon_name' => 'Activity',
            'image' => $imgPasta,
            'highlights' => [
                'Inspeção eletrônica por mapeamento de calor (câmera térmica)',
                'Estação de solda SMD e retrabalho de chips',
                'Orçamento transparente sem cobrança indevida de placa nova',
                'Desoxidação ultrassônica em equipamentos que molharam',
            ],
            'recommended_for' => [
                'Notebook parou de ligar de repente após raio ou queda de luz',
                'Equipamento que teve líquido derramado (água, café, suco)',
                'Led do conector acende mas o botão power não responde',
                'Cheiro de queimado ou faiscamento na carcaça',
            ],
        ],
        [
            'slug' => 'formatacao-instalacao-sistemas',
            'title' => 'Formatação e Instalação de Sistemas',
            'short_desc' => 'Instalação limpa de Windows 11/10 e Linux com drivers homologados e backup prévio de segurança.',
            'full_desc' => 'Restaure o desempenho original de fábrica do seu sistema. Realizamos backup rigoroso e estruturado de todas as suas pastas pessoais (Documentos, Fotos, Área de Trabalho e Favoritos) com verificação de integridade antes da formatação. Instalamos a versão mais estável do Windows 11, Windows 10 ou distribuição Linux com drivers proprietários dos fabricantes.',
            'category' => 'software',
            'price_starting_at' => 80,
            'turnaround_time' => '24 horas',
            'warranty_days' => 90,
            'icon_name' => 'Terminal',
            'image' => $imgWorkstation,
            'highlights' => [
                'Backup completo sem risco de perda de arquivos importantes',
                'Instalação de navegadores, leitores de PDF e pacotes essenciais',
                'Atualizações oficiais de segurança do Windows Update homologadas',
                'Limpeza de bloatwares e programas pré-instalados desnecessários',
            ],
            'recommended_for' => [
                'Sistema corrompido que fica em looping de reparo automático',
                'Tela azul da morte (BSOD) frequente',
                'Lentidão extrema acumulada após anos de uso',
                'Troca de proprietário ou preparação para revenda',
            ],
        ],
        [
            'slug' => 'remocao-virus-seguranca',
            'title' => 'Remoção de Vírus e Segurança Digital',
            'short_desc' => 'Varredura e desinfecção profunda de malwares, adwares e spywares com proteção da privacidade de dados.',
            'full_desc' => 'Eliminação completa de ameaças virtuais ocultas que roubam senhas, sequestram arquivos ou usam seu computador para mineração oculta de criptomoedas. Higienizamos o registro do sistema operacional, eliminamos extensões maliciosas de navegadores e implementamos antivírus configurado com proteção em tempo real.',
            'category' => 'software',
            'price_starting_at' => 90,
            'turnaround_time' => '24 horas',
            'warranty_days' => 90,
            'icon_name' => 'Shield',
            'image' => $imgBancada,
            'highlights' => [
                'Desinfecção com ferramentas laboratoriais de alta precisão',
                'Eliminação de spywares, trojans e sequestradores de busca',
                'Preservação total dos arquivos pessoais do usuário',
                'Orientação preventiva de segurança digital',
            ],
            'recommended_for' => [
                'Janelas e anúncios abrindo sozinhos na área de trabalho',
                'Navegador redirecionando para sites desconhecidos',
                'Uso da CPU em 100% mesmo sem nenhum programa aberto',
                'Suspeita de invasão ou vazamento de credenciais',
            ],
        ],
        [
            'slug' => 'limpeza-preventiva-termica',
            'title' => 'Limpeza Preventiva e Manutenção Térmica',
            'short_desc' => 'Higienização interna, desobstrução de coolers e troca de pasta térmica premium para redução de temperatura.',
            'full_desc' => 'Evite a queima prematura do processador e da placa de vídeo. Desmontamos o equipamento por completo para remoção de poeira acumulada, maresia comum em cidades litorâneas como João Pessoa, desobstrução das aletas dos dissipadores e substituição da pasta ressecada por compostos de alta condutividade térmica (Arctic MX-4/MX-6 e Thermal Pads de alto desempenho).',
            'category' => 'preventiva',
            'price_starting_at' => 110,
            'turnaround_time' => 'Mesmo dia ou 24h',
            'warranty_days' => 90,
            'icon_name' => 'Fan',
            'image' => $imgPasta,
            'highlights' => [
                'Redução comprovada de até 15°C a 25°C sob carga',
                'Aplicação de pastas térmicas homologadas internacionalmente',
                'Lubrificação de rolamentos dos coolers para operação silenciosa',
                'Tratamento preventivo contra oxidação e maresia paraibana',
            ],
            'recommended_for' => [
                'Notebook muito quente ao toque no teclado ou na base',
                'Ventoinha girando no máximo o tempo inteiro com barulho alto',
                'Quedas bruscas de desempenho em jogos (thermal throttling)',
                'Equipamentos com mais de 1 ano sem revisão técnica interna',
            ],
        ],
        [
            'slug' => 'suporte-tecnico-empresarial',
            'title' => 'Suporte Técnico Empresarial e Contratos PJ',
            'short_desc' => 'Planos corporativos de manutenção para clínicas, comércios e escritórios com atendimento ágil.',
            'full_desc' => 'Solução estruturada para manter a operação da sua empresa sem interrupções. Atendemos consultórios médicos, escritórios de advocacia, contabilidades e comércios da Grande João Pessoa com planos de manutenção preventiva mensal, suporte remoto emergencial, configuração de redes corporativas e rotinas automatizadas de backup.',
            'category' => 'corporativo',
            'price_starting_at' => 350,
            'turnaround_time' => 'SLA de 2h a 4h',
            'warranty_days' => 90,
            'icon_name' => 'Building',
            'image' => $imgWorkstation,
            'highlights' => [
                'Emissão de Nota Fiscal de Serviços eletrônica e relatórios técnicos',
                'Suporte remoto imediato para resolução de chamados diários',
                'Padronização de sistemas e política rigorosa de segurança LGPD',
                'Atendimento prioritário presencial na empresa',
            ],
            'recommended_for' => [
                'Clínicas e consultórios que não podem parar recepção e prontuário',
                'Escritórios com parque de 3 a 30 computadores',
                'Empresas que necessitam de backups diários em nuvem protegidos',
                'Comércios com pontos de venda (PDV) e servidores locais',
            ],
        ],
    ],

    'leads' => [
        [
            'protocol' => 'OS-2026-0842',
            'customer_name' => 'Renata Albuquerque',
            'phone' => '(83) 98845-1234',
            'email' => 'renata.albuquerque@gmail.com',
            'city' => 'João Pessoa (Manaíra)',
            'device_type' => 'notebook',
            'service_type' => 'Limpeza preventiva e troca de pasta térmica',
            'description' => 'Notebook Dell Inspiron esquentando muito e desligando sozinho após 20 minutos de uso. Preciso de revisão técnica antes de viajar.',
            'status' => 'em_execucao',
            'estimated_budget' => 150,
            'final_budget' => 150,
            'internal_notes' => 'Desmontagem concluída. Pasta antiga totalmente ressecada. Aplicado Arctic MX-6 e feita desobstrução de cooler. Em fase de testes de estresse.',
            'created_at' => '2026-10-05 09:30:00',
            'updated_at' => '2026-10-05 14:15:00',
        ],
        [
            'protocol' => 'OS-2026-0841',
            'customer_name' => 'Dr. Lucas Medeiros',
            'phone' => '(83) 99120-7788',
            'email' => 'lucasmedeiros.adv@outlook.com',
            'city' => 'Cabedelo (Intermares)',
            'device_type' => 'notebook',
            'service_type' => 'Upgrade de SSD / Memória RAM',
            'description' => 'Lenovo ThinkPad com HD mecânico muito lento ao abrir processos e PDFs pesados. Desejo colocar SSD NVMe de 1TB e clonar o sistema sem perder nada.',
            'status' => 'concluido',
            'estimated_budget' => 420,
            'final_budget' => 420,
            'internal_notes' => 'Clonado com sucesso para SSD Kingston NV2 1TB NVMe. Tempo de boot reduziu de 3min15s para 9 segundos. Cliente já notificado via WhatsApp.',
            'created_at' => '2026-10-04 15:10:00',
            'updated_at' => '2026-10-05 11:00:00',
        ],
        [
            'protocol' => 'OS-2026-0840',
            'customer_name' => 'Mariana Farias',
            'phone' => '(83) 98733-4411',
            'email' => 'mari.farias92@gmail.com',
            'city' => 'João Pessoa (Bancários)',
            'device_type' => 'notebook',
            'service_type' => 'Reparo de placa-mãe / Não liga',
            'description' => 'Acer Nitro 5 parou de ligar após forte chuva com oscilação na rede elétrica. Nem acende a luz do carregador.',
            'status' => 'em_diagnostico',
            'estimated_budget' => 280,
            'final_budget' => null,
            'internal_notes' => 'Identificado curto no MOSFET de entrada da linha de 19V na placa-mãe. Componente sob teste na bancada ESD. Aguardando conclusão da medição.',
            'created_at' => '2026-10-05 11:45:00',
            'updated_at' => '2026-10-05 15:20:00',
        ],
        [
            'protocol' => 'OS-2026-0839',
            'customer_name' => 'Clínica Odonto Prime (Dra. Juliana)',
            'phone' => '(83) 99650-2020',
            'email' => 'atendimento@odontoprimejp.com.br',
            'city' => 'João Pessoa (Tambaú)',
            'device_type' => 'corporativo',
            'service_type' => 'Suporte técnico empresarial',
            'description' => 'Computador da recepção travando no sistema de prontuário e backup parou de sincronizar na nuvem.',
            'status' => 'aguardando_aprovacao',
            'estimated_budget' => 350,
            'final_budget' => null,
            'internal_notes' => 'Orçamento enviado para a secretária. Proposta de suporte avulso com otimização do banco de dados e configuração de rotina automática no Google Drive.',
            'created_at' => '2026-10-04 17:20:00',
            'updated_at' => '2026-10-05 10:10:00',
        ],
        [
            'protocol' => 'OS-2026-0838',
            'customer_name' => 'Carlos Henrique Vilar',
            'phone' => '(83) 98114-9988',
            'email' => null,
            'city' => 'Santa Rita',
            'device_type' => 'desktop',
            'service_type' => 'Diagnóstico geral de falha',
            'description' => 'PC Gamer montado liga as luzes dos fans mas não dá vídeo na placa RTX 3060. Testei outro cabo HDMI e não resolveu.',
            'status' => 'pendente',
            'estimated_budget' => null,
            'final_budget' => null,
            'internal_notes' => null,
            'created_at' => '2026-10-05 14:50:00',
            'updated_at' => '2026-10-05 14:50:00',
        ],
        [
            'protocol' => 'OS-2026-0837',
            'customer_name' => 'Tiago Queiroz',
            'phone' => '(83) 98888-3344',
            'email' => null,
            'city' => 'Bayeux',
            'device_type' => 'notebook',
            'service_type' => 'Formatação e instalação de sistema',
            'description' => 'Formatação com backup de 80GB de fotos e documentos. Instalação do Windows 11 oficial.',
            'status' => 'entregue',
            'estimated_budget' => 120,
            'final_budget' => 120,
            'internal_notes' => 'Equipamento testado, assinado termo de entrega e garantia entregue ao cliente.',
            'created_at' => '2026-10-03 10:00:00',
            'updated_at' => '2026-10-04 16:30:00',
        ],
    ],

    'testimonials' => [
        [
            'author' => 'Cláudio Silveira',
            'location' => 'Manaíra, João Pessoa',
            'rating' => 5,
            'text' => 'Excelente atendimento técnico. O notebook estava travando e superaquecendo, fizeram a limpeza e upgrade de SSD no mesmo dia. Máquina virou um foguete!',
            'service_title' => 'Limpeza térmica e Upgrade SSD',
            'testimonial_date' => '2026-09-28',
            'verified' => 1,
            'approved' => 1,
        ],
        [
            'author' => 'Dra. Gabriela Vasconcelos',
            'location' => 'Intermares, Cabedelo',
            'rating' => 5,
            'text' => 'Transparência total no orçamento. Explicaram exatamente o componente danificado na placa-mãe antes de iniciar o serviço. Salvaram meu notebook de trabalho.',
            'service_title' => 'Reparo de placa-mãe',
            'testimonial_date' => '2026-09-22',
            'verified' => 1,
            'approved' => 1,
        ],
        [
            'author' => 'Roberto Neves (Studio Design)',
            'location' => 'Altiplano, João Pessoa',
            'rating' => 5,
            'text' => 'Profissionais honestos e pontuais. Montaram minha workstation com organização impecável dos cabos e testes térmicos. Recomendo de olhos fechados.',
            'service_title' => 'Montagem de Workstation',
            'testimonial_date' => '2026-09-15',
            'verified' => 1,
            'approved' => 1,
        ],
        [
            'author' => 'Fernanda Diniz',
            'location' => 'Bessa, João Pessoa',
            'rating' => 5,
            'text' => 'O serviço de Leva e Traz facilitou muito minha vida na semana corrida de trabalho. O computador voltou limpinho e funcionando perfeitamente.',
            'service_title' => 'Leva e Traz + Formatação',
            'testimonial_date' => '2026-10-02',
            'verified' => 1,
            'approved' => 1,
        ],
    ],

    'faqs' => [
        [
            'question' => 'Quais equipamentos são atendidos?',
            'answer' => 'Atendemos notebooks de todas as marcas (Dell, Lenovo, HP, Acer, Asus, Apple MacBook, Samsung) e computadores desktop convencionais, estações de trabalho e gabinetes gamer.',
            'category' => 'Geral',
        ],
        [
            'question' => 'Como solicitar um orçamento?',
            'answer' => 'Basta entrar em contato pelo WhatsApp informando o modelo do equipamento e o problema apresentado, ou preencher o formulário nesta página para receber retorno com as orientações técnicas.',
            'category' => 'Atendimento',
        ],
        [
            'question' => 'Vocês atendem empresas e emitem Nota Fiscal?',
            'answer' => 'Sim! Atendemos clínicas, escritórios e comércios com contratos de manutenção preventiva, suporte remoto avulso e emissão formal de NFS-e (Nota Fiscal de Serviços Eletrônica).',
            'category' => 'Empresas',
        ],
        [
            'question' => 'Quais cidades fazem parte da área de atendimento?',
            'answer' => 'Atendemos diretamente João Pessoa, Cabedelo, Bayeux e Santa Rita, além de cidades vizinhas da região metropolitana mediante agendamento prévio ou serviço de leva e traz.',
            'category' => 'Região',
        ],
        [
            'question' => 'Como funciona o diagnóstico técnico?',
            'answer' => 'O aparelho passa por testes de bancada com medições elétricas, teste de estresse e verificação de integridade dos componentes em bancada ESD, assegurando um diagnóstico seguro antes de qualquer intervenção.',
            'category' => 'Técnico',
        ],
        [
            'question' => 'Qual é o prazo de garantia dos serviços executados?',
            'answer' => 'Todos os nossos serviços de manutenção e substituição de peças contam com garantia legal e estendida de 90 dias, assegurada por ordem de serviço e termo de entrega.',
            'category' => 'Garantia',
        ],
    ],

    'cities' => [
        [
            'name' => 'João Pessoa',
            'coverage' => 'Todos os bairros (Manaíra, Tambaú, Bessa, Cabo Branco, Bancários, Jaguaribe, Centro, Altiplano, etc.)',
            'delivery_available' => 1,
            'delivery_fee' => 0,
            'notes' => 'Atendimento presencial em bancada, domiciliar e serviço de Leva e Traz gratuito para serviços acima de R$ 150.',
        ],
        [
            'name' => 'Cabedelo',
            'coverage' => 'Intermares, Renascer, Poço, Camboinha, Formosa e Centro',
            'delivery_available' => 1,
            'delivery_fee' => 20,
            'notes' => 'Atendimento corporativo e residencial com agendamento diário e rota de coleta.',
        ],
        [
            'name' => 'Bayeux',
            'coverage' => 'Centro, Mário Andreazza, Imaculada, Alto da Boa Vista e adjacências',
            'delivery_available' => 1,
            'delivery_fee' => 15,
            'notes' => 'Rota matutina e vespertina de coleta técnica.',
        ],
        [
            'name' => 'Santa Rita',
            'coverage' => 'Tibiri II, Centro, Várzea Nova, Marcos Moura e adjacências',
            'delivery_available' => 1,
            'delivery_fee' => 25,
            'notes' => 'Suporte a residências e comércios locais.',
        ],
        [
            'name' => 'Conde',
            'coverage' => 'Centro e Litoral Sul (Jacumã, Carapibus, Tabatinga)',
            'delivery_available' => 1,
            'delivery_fee' => 35,
            'notes' => 'Atendimento agendado semanalmente para empresas e pousadas.',
        ],
        [
            'name' => 'Lucena',
            'coverage' => 'Centro e orla de Lucena',
            'delivery_available' => 1,
            'delivery_fee' => 40,
            'notes' => 'Atendimento sob agendamento prévio com confirmação de rota.',
        ],
        [
            'name' => 'Alhandra',
            'coverage' => 'Área urbana e polo industrial',
            'delivery_available' => 1,
            'delivery_fee' => 45,
            'notes' => 'Foco em suporte a empresas e indústrias da região.',
        ],
        [
            'name' => 'Caaporã',
            'coverage' => 'Área urbana e distritos vizinhos',
            'delivery_available' => 1,
            'delivery_fee' => 50,
            'notes' => 'Sob consulta com a coordenação técnica.',
        ],
        [
            'name' => 'Pedras de Fogo',
            'coverage' => 'Área central e comercial',
            'delivery_available' => 1,
            'delivery_fee' => 50,
            'notes' => 'Sob consulta de rota e demanda técnica.',
        ],
    ],

    'user' => [
        'name' => 'Carlos Eduardo Oliveira',
        'email' => 'carlos.eduardo@pcresolvejp.com.br',
        'phone' => '(83) 98822-1010',
        'role' => 'superadmin',
        'avatar' => $imgWorkstation,
        'department' => 'Coordenação Técnica & Gestão',
        'notify_email_new_lead' => 1,
        'notify_whatsapp_alerts' => 1,
        'notify_browser_sound' => 1,
    ],

    'analytics' => [
        'hoje' => [
            'summary' => [
                'totalVisits' => 142, 'uniqueVisitors' => 118, 'pageViews' => 412, 'avgTimeOnSite' => '2m 45s',
                'bounceRate' => '28.4%', 'conversionRate' => '8.4%', 'totalLeads' => 12, 'whatsappClicks' => 9, 'phoneCalls' => 3,
            ],
            'dailyVisits' => [
                ['date' => '08:00', 'visitors' => 8, 'pageViews' => 22, 'leads' => 1],
                ['date' => '10:00', 'visitors' => 26, 'pageViews' => 84, 'leads' => 2],
                ['date' => '12:00', 'visitors' => 19, 'pageViews' => 54, 'leads' => 1],
                ['date' => '14:00', 'visitors' => 34, 'pageViews' => 112, 'leads' => 4],
                ['date' => '16:00', 'visitors' => 38, 'pageViews' => 98, 'leads' => 3],
                ['date' => '18:00', 'visitors' => 17, 'pageViews' => 42, 'leads' => 1],
            ],
            'trafficSources' => [
                ['source' => 'Google Orgânico (SEO)', 'visits' => 68, 'percentage' => 48, 'conversions' => 6],
                ['source' => 'Google Meu Negócio (Maps)', 'visits' => 41, 'percentage' => 29, 'conversions' => 4],
                ['source' => 'Acesso Direto / Cartão', 'visits' => 18, 'percentage' => 13, 'conversions' => 1],
                ['source' => 'Instagram / Redes Sociais', 'visits' => 15, 'percentage' => 10, 'conversions' => 1],
            ],
            'cityStats' => [
                ['city' => 'João Pessoa', 'visits' => 95, 'percentage' => 67, 'leads' => 8],
                ['city' => 'Cabedelo', 'visits' => 24, 'percentage' => 17, 'leads' => 2],
                ['city' => 'Bayeux', 'visits' => 12, 'percentage' => 8, 'leads' => 1],
                ['city' => 'Santa Rita', 'visits' => 8, 'percentage' => 6, 'leads' => 1],
                ['city' => 'Conde / Outros', 'visits' => 3, 'percentage' => 2, 'leads' => 0],
            ],
            'deviceBreakdown' => [
                ['device' => 'Mobile (Smartphones)', 'percentage' => 71, 'visits' => 101],
                ['device' => 'Desktop / Notebook', 'percentage' => 26, 'visits' => 37],
                ['device' => 'Tablet', 'percentage' => 3, 'visits' => 4],
            ],
            'topPages' => [
                ['path' => '/', 'title' => 'Início | Assistência Técnica João Pessoa', 'views' => 184, 'uniqueViews' => 118, 'avgTime' => '1m 50s', 'conversionCount' => 5],
                ['path' => '/servicos', 'title' => 'Catálogo de Serviços', 'views' => 98, 'uniqueViews' => 72, 'avgTime' => '2m 10s', 'conversionCount' => 3],
                ['path' => '/servicos/manutencao-notebooks', 'title' => 'Manutenção de Notebooks', 'views' => 56, 'uniqueViews' => 44, 'avgTime' => '3m 05s', 'conversionCount' => 2],
                ['path' => '/servicos/upgrade-ssd-memoria', 'title' => 'Upgrade de SSD e Memória RAM', 'views' => 42, 'uniqueViews' => 35, 'avgTime' => '2m 40s', 'conversionCount' => 2],
                ['path' => '/contato', 'title' => 'Solicitar Orçamento', 'views' => 32, 'uniqueViews' => 28, 'avgTime' => '1m 15s', 'conversionCount' => 0],
            ],
            'conversionFunnel' => [
                ['stage' => '1. Visitantes no Site', 'count' => 142, 'percentage' => 100],
                ['stage' => '2. Visualizou Página de Serviços', 'count' => 98, 'percentage' => 69],
                ['stage' => '3. Acessou Detalhes / Formulário', 'count' => 48, 'percentage' => 34],
                ['stage' => '4. Lead Gerado (WhatsApp / Formulário)', 'count' => 12, 'percentage' => 8.4],
            ],
        ],
        '7dias' => [
            'summary' => [
                'totalVisits' => 1084, 'uniqueVisitors' => 842, 'pageViews' => 3240, 'avgTimeOnSite' => '2m 38s',
                'bounceRate' => '29.1%', 'conversionRate' => '7.8%', 'totalLeads' => 85, 'whatsappClicks' => 62, 'phoneCalls' => 23,
            ],
            'dailyVisits' => [
                ['date' => 'Segunda', 'visitors' => 165, 'pageViews' => 520, 'leads' => 14],
                ['date' => 'Terça', 'visitors' => 182, 'pageViews' => 574, 'leads' => 16],
                ['date' => 'Quarta', 'visitors' => 194, 'pageViews' => 610, 'leads' => 18],
                ['date' => 'Quinta', 'visitors' => 178, 'pageViews' => 540, 'leads' => 13],
                ['date' => 'Sexta', 'visitors' => 162, 'pageViews' => 490, 'leads' => 12],
                ['date' => 'Sábado', 'visitors' => 115, 'pageViews' => 310, 'leads' => 8],
                ['date' => 'Domingo', 'visitors' => 88, 'pageViews' => 196, 'leads' => 4],
            ],
            'trafficSources' => [
                ['source' => 'Google Orgânico (SEO)', 'visits' => 520, 'percentage' => 48, 'conversions' => 42],
                ['source' => 'Google Meu Negócio (Maps)', 'visits' => 314, 'percentage' => 29, 'conversions' => 27],
                ['source' => 'Acesso Direto / Cartão', 'visits' => 141, 'percentage' => 13, 'conversions' => 9],
                ['source' => 'Instagram / Redes Sociais', 'visits' => 109, 'percentage' => 10, 'conversions' => 7],
            ],
            'cityStats' => [
                ['city' => 'João Pessoa', 'visits' => 726, 'percentage' => 67, 'leads' => 59],
                ['city' => 'Cabedelo', 'visits' => 184, 'percentage' => 17, 'leads' => 15],
                ['city' => 'Bayeux', 'visits' => 87, 'percentage' => 8, 'leads' => 6],
                ['city' => 'Santa Rita', 'visits' => 54, 'percentage' => 5, 'leads' => 3],
                ['city' => 'Conde / Litoral Sul', 'visits' => 33, 'percentage' => 3, 'leads' => 2],
            ],
            'deviceBreakdown' => [
                ['device' => 'Mobile (Smartphones)', 'percentage' => 69, 'visits' => 748],
                ['device' => 'Desktop / Notebook', 'percentage' => 28, 'visits' => 303],
                ['device' => 'Tablet', 'percentage' => 3, 'visits' => 33],
            ],
            'topPages' => [
                ['path' => '/', 'title' => 'Início | Assistência Técnica João Pessoa', 'views' => 1420, 'uniqueViews' => 842, 'avgTime' => '1m 55s', 'conversionCount' => 38],
                ['path' => '/servicos', 'title' => 'Catálogo de Serviços', 'views' => 760, 'uniqueViews' => 520, 'avgTime' => '2m 15s', 'conversionCount' => 21],
                ['path' => '/servicos/manutencao-notebooks', 'title' => 'Manutenção de Notebooks', 'views' => 410, 'uniqueViews' => 312, 'avgTime' => '3m 10s', 'conversionCount' => 12],
                ['path' => '/servicos/upgrade-ssd-memoria', 'title' => 'Upgrade de SSD e Memória RAM', 'views' => 335, 'uniqueViews' => 248, 'avgTime' => '2m 50s', 'conversionCount' => 8],
                ['path' => '/areas-atendidas', 'title' => 'Cidades Atendidas Grande JP', 'views' => 185, 'uniqueViews' => 140, 'avgTime' => '1m 40s', 'conversionCount' => 4],
                ['path' => '/contato', 'title' => 'Solicitar Orçamento', 'views' => 130, 'uniqueViews' => 110, 'avgTime' => '1m 20s', 'conversionCount' => 2],
            ],
            'conversionFunnel' => [
                ['stage' => '1. Visitantes no Site', 'count' => 1084, 'percentage' => 100],
                ['stage' => '2. Visualizou Página de Serviços', 'count' => 760, 'percentage' => 70],
                ['stage' => '3. Acessou Detalhes / Formulário', 'count' => 380, 'percentage' => 35],
                ['stage' => '4. Lead Gerado (WhatsApp / Formulário)', 'count' => 85, 'percentage' => 7.8],
            ],
        ],
        '30dias' => [
            'summary' => [
                'totalVisits' => 4720, 'uniqueVisitors' => 3650, 'pageViews' => 14160, 'avgTimeOnSite' => '2m 42s',
                'bounceRate' => '28.9%', 'conversionRate' => '8.1%', 'totalLeads' => 382, 'whatsappClicks' => 284, 'phoneCalls' => 98,
            ],
            'dailyVisits' => [
                ['date' => 'Semana 1', 'visitors' => 1120, 'pageViews' => 3360, 'leads' => 91],
                ['date' => 'Semana 2', 'visitors' => 1180, 'pageViews' => 3540, 'leads' => 96],
                ['date' => 'Semana 3', 'visitors' => 1240, 'pageViews' => 3720, 'leads' => 102],
                ['date' => 'Semana 4', 'visitors' => 1180, 'pageViews' => 3540, 'leads' => 93],
            ],
            'trafficSources' => [
                ['source' => 'Google Orgânico (SEO)', 'visits' => 2265, 'percentage' => 48, 'conversions' => 188],
                ['source' => 'Google Meu Negócio (Maps)', 'visits' => 1369, 'percentage' => 29, 'conversions' => 115],
                ['source' => 'Acesso Direto / Cartão', 'visits' => 614, 'percentage' => 13, 'conversions' => 48],
                ['source' => 'Instagram / Redes Sociais', 'visits' => 472, 'percentage' => 10, 'conversions' => 31],
            ],
            'cityStats' => [
                ['city' => 'João Pessoa', 'visits' => 3162, 'percentage' => 67, 'leads' => 260],
                ['city' => 'Cabedelo', 'visits' => 802, 'percentage' => 17, 'leads' => 64],
                ['city' => 'Bayeux', 'visits' => 378, 'percentage' => 8, 'leads' => 29],
                ['city' => 'Santa Rita', 'visits' => 236, 'percentage' => 5, 'leads' => 18],
                ['city' => 'Conde / Litoral Sul', 'visits' => 142, 'percentage' => 3, 'leads' => 11],
            ],
            'deviceBreakdown' => [
                ['device' => 'Mobile (Smartphones)', 'percentage' => 68, 'visits' => 3210],
                ['device' => 'Desktop / Notebook', 'percentage' => 29, 'visits' => 1369],
                ['device' => 'Tablet', 'percentage' => 3, 'visits' => 141],
            ],
            'topPages' => [
                ['path' => '/', 'title' => 'Início | Assistência Técnica João Pessoa', 'views' => 6240, 'uniqueViews' => 3650, 'avgTime' => '1m 58s', 'conversionCount' => 168],
                ['path' => '/servicos', 'title' => 'Catálogo de Serviços', 'views' => 3310, 'uniqueViews' => 2280, 'avgTime' => '2m 18s', 'conversionCount' => 94],
                ['path' => '/servicos/manutencao-notebooks', 'title' => 'Manutenção de Notebooks', 'views' => 1820, 'uniqueViews' => 1340, 'avgTime' => '3m 12s', 'conversionCount' => 52],
                ['path' => '/servicos/upgrade-ssd-memoria', 'title' => 'Upgrade de SSD e Memória RAM', 'views' => 1450, 'uniqueViews' => 1080, 'avgTime' => '2m 54s', 'conversionCount' => 36],
                ['path' => '/areas-atendidas', 'title' => 'Cidades Atendidas Grande JP', 'views' => 780, 'uniqueViews' => 610, 'avgTime' => '1m 45s', 'conversionCount' => 18],
                ['path' => '/contato', 'title' => 'Solicitar Orçamento', 'views' => 560, 'uniqueViews' => 490, 'avgTime' => '1m 25s', 'conversionCount' => 14],
            ],
            'conversionFunnel' => [
                ['stage' => '1. Visitantes no Site', 'count' => 4720, 'percentage' => 100],
                ['stage' => '2. Visualizou Página de Serviços', 'count' => 3310, 'percentage' => 70],
                ['stage' => '3. Acessou Detalhes / Formulário', 'count' => 1650, 'percentage' => 35],
                ['stage' => '4. Lead Gerado (WhatsApp / Formulário)', 'count' => 382, 'percentage' => 8.1],
            ],
        ],
        'mes' => [
            'summary' => [
                'totalVisits' => 5210, 'uniqueVisitors' => 4020, 'pageViews' => 15630, 'avgTimeOnSite' => '2m 44s',
                'bounceRate' => '28.5%', 'conversionRate' => '8.3%', 'totalLeads' => 432, 'whatsappClicks' => 320, 'phoneCalls' => 112,
            ],
            'dailyVisits' => [
                ['date' => '01 a 07', 'visitors' => 1180, 'pageViews' => 3540, 'leads' => 98],
                ['date' => '08 a 14', 'visitors' => 1240, 'pageViews' => 3720, 'leads' => 104],
                ['date' => '15 a 21', 'visitors' => 1320, 'pageViews' => 3960, 'leads' => 112],
                ['date' => '22 a 28', 'visitors' => 1190, 'pageViews' => 3570, 'leads' => 96],
                ['date' => '29 a 31', 'visitors' => 280, 'pageViews' => 840, 'leads' => 22],
            ],
            'trafficSources' => [
                ['source' => 'Google Orgânico (SEO)', 'visits' => 2501, 'percentage' => 48, 'conversions' => 212],
                ['source' => 'Google Meu Negócio (Maps)', 'visits' => 1511, 'percentage' => 29, 'conversions' => 129],
                ['source' => 'Acesso Direto / Cartão', 'visits' => 677, 'percentage' => 13, 'conversions' => 54],
                ['source' => 'Instagram / Redes Sociais', 'visits' => 521, 'percentage' => 10, 'conversions' => 37],
            ],
            'cityStats' => [
                ['city' => 'João Pessoa', 'visits' => 3491, 'percentage' => 67, 'leads' => 292],
                ['city' => 'Cabedelo', 'visits' => 886, 'percentage' => 17, 'leads' => 74],
                ['city' => 'Bayeux', 'visits' => 417, 'percentage' => 8, 'leads' => 34],
                ['city' => 'Santa Rita', 'visits' => 260, 'percentage' => 5, 'leads' => 21],
                ['city' => 'Conde / Litoral Sul', 'visits' => 156, 'percentage' => 3, 'leads' => 11],
            ],
            'deviceBreakdown' => [
                ['device' => 'Mobile (Smartphones)', 'percentage' => 68, 'visits' => 3543],
                ['device' => 'Desktop / Notebook', 'percentage' => 29, 'visits' => 1511],
                ['device' => 'Tablet', 'percentage' => 3, 'visits' => 156],
            ],
            'topPages' => [
                ['path' => '/', 'title' => 'Início | Assistência Técnica João Pessoa', 'views' => 6890, 'uniqueViews' => 4020, 'avgTime' => '2m 00s', 'conversionCount' => 190],
                ['path' => '/servicos', 'title' => 'Catálogo de Serviços', 'views' => 3650, 'uniqueViews' => 2510, 'avgTime' => '2m 20s', 'conversionCount' => 108],
                ['path' => '/servicos/manutencao-notebooks', 'title' => 'Manutenção de Notebooks', 'views' => 2010, 'uniqueViews' => 1480, 'avgTime' => '3m 15s', 'conversionCount' => 58],
                ['path' => '/servicos/upgrade-ssd-memoria', 'title' => 'Upgrade de SSD e Memória RAM', 'views' => 1610, 'uniqueViews' => 1190, 'avgTime' => '2m 58s', 'conversionCount' => 42],
                ['path' => '/areas-atendidas', 'title' => 'Cidades Atendidas Grande JP', 'views' => 860, 'uniqueViews' => 680, 'avgTime' => '1m 48s', 'conversionCount' => 21],
                ['path' => '/contato', 'title' => 'Solicitar Orçamento', 'views' => 610, 'uniqueViews' => 530, 'avgTime' => '1m 30s', 'conversionCount' => 13],
            ],
            'conversionFunnel' => [
                ['stage' => '1. Visitantes no Site', 'count' => 5210, 'percentage' => 100],
                ['stage' => '2. Visualizou Página de Serviços', 'count' => 3650, 'percentage' => 70],
                ['stage' => '3. Acessou Detalhes / Formulário', 'count' => 1820, 'percentage' => 35],
                ['stage' => '4. Lead Gerado (WhatsApp / Formulário)', 'count' => 432, 'percentage' => 8.3],
            ],
        ],
    ],
];
